#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 017

set -e

echo "========================================"
echo "Django Test Environment Setup"
echo "Task: Add tests for production and purchasing apps"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if we're in the right directory
if [ ! -f "manage.py" ]; then
    echo -e "${RED}Error: manage.py not found. Are you in the project root?${NC}"
    exit 1
fi

# ============================================
# SETUP DJANGO TEST ENVIRONMENT
# ============================================

echo ""
echo "Setting up Django test environment..."

# Check if PostgreSQL is running (if using docker-compose)
if [ -f "docker-compose.yml" ]; then
    echo "Checking Docker Compose services..."
    docker-compose ps
fi

# Run migrations to ensure test database is up to date
echo ""
echo "Running database migrations..."
python manage.py migrate --noinput

# Create a superuser for testing if needed (optional)
echo ""
echo "Database ready for testing"

# ============================================
# VERIFY EXISTING TESTS
# ============================================

echo ""
echo "Verifying existing test suite..."
echo "Running tests for inventory, materials, and accounts apps..."

python manage.py test apps.inventory apps.materials apps.accounts --verbosity=2

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Existing tests passed successfully${NC}"
else
    echo -e "${RED}Warning: Some existing tests failed${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Test Development!"
echo "========================================"
echo ""
echo "Project Structure:"
echo "  - Django project with multiple apps"
echo "  - Test framework: Django TestCase"
echo "  - Apps to test: production (5 models), purchasing (6 models)"
echo ""
echo "Reference test files:"
echo "  - apps/inventory/tests.py (590 lines)"
echo "  - apps/materials/tests.py (366 lines)"
echo "  - apps/accounts/tests.py (379 lines)"
echo ""
echo "Next Steps:"
echo "  1. Create apps/production/tests.py"
echo "  2. Create apps/purchasing/tests.py"
echo "  3. Run tests: python manage.py test"
echo ""
echo "To run tests during development:"
echo "  - Production tests: python manage.py test apps.production"
echo "  - Purchasing tests: python manage.py test apps.purchasing"
echo "  - All tests: python manage.py test"
echo ""
