# Generated by Django 6.0.1 on 2026-01-26 21:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numero do Pedido",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("SENT", "Enviado ao Fornecedor"),
                            ("CONFIRMED", "Confirmado"),
                            ("PARTIAL", "Parcialmente Recebido"),
                            ("RECEIVED", "Recebido"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data do Pedido"
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Prevista de Entrega"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Condicoes de Pagamento",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="Endereco de Entrega"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comprador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="materials.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="inventory.warehouse",
                        verbose_name="Armazem Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Compra",
                "verbose_name_plural": "Pedidos de Compra",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade (kg)",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Preco Unitario (R$/kg)",
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Quantidade Recebida",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_items",
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.purchaseorder",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Itens de Pedido",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numero de Referencia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PENDING", "Aguardando Aprovacao"),
                            ("APPROVED", "Aprovada"),
                            ("REJECTED", "Rejeitada"),
                            ("ORDERED", "Pedido Gerado"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baixa"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "Alta"),
                            ("URGENT", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Solicitacao",
                    ),
                ),
                (
                    "required_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Necessaria"
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justificativa"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Aprovacao"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo da Rejeicao"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requests",
                        to="inventory.warehouse",
                        verbose_name="Armazem Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitacao de Compra",
                "verbose_name_plural": "Solicitacoes de Compra",
                "ordering": ["-request_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="purchase_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="purchasing.purchaserequest",
                verbose_name="Solicitacao de Origem",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseRequestItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade (kg)",
                    ),
                ),
                (
                    "estimated_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preco Unitario Estimado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_request_items",
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "preferred_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_request_items",
                        to="materials.supplier",
                        verbose_name="Fornecedor Preferencial",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.purchaserequest",
                        verbose_name="Solicitacao",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Solicitacao",
                "verbose_name_plural": "Itens de Solicitacao",
            },
        ),
        migrations.CreateModel(
            name="Receiving",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numero do Recebimento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("INSPECTING", "Em Inspecao"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                            ("PARTIAL", "Parcialmente Aprovado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "receiving_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data do Recebimento",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numero da Nota Fiscal"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Nota Fiscal"
                    ),
                ),
                (
                    "inspection_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Inspecao"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo da Rejeicao"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_receivings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inspecionado por",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivings",
                        to="purchasing.purchaseorder",
                        verbose_name="Pedido de Compra",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recebido por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebimento",
                "verbose_name_plural": "Recebimentos",
                "ordering": ["-receiving_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade Recebida (kg)",
                    ),
                ),
                (
                    "quantity_accepted",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Quantidade Aceita (kg)",
                    ),
                ),
                (
                    "quantity_rejected",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Quantidade Rejeitada (kg)",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numero do Lote"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo da Rejeicao"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_items",
                        to="purchasing.purchaseorderitem",
                        verbose_name="Item do Pedido",
                    ),
                ),
                (
                    "receiving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.receiving",
                        verbose_name="Recebimento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Recebimento",
                "verbose_name_plural": "Itens de Recebimento",
            },
        ),
    ]
