# Generated by Django 5.2.4 on 2026-01-27 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_indexes'),
        ('materials', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchasing__status_04b4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchasing__order_d_09a604_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['is_active'], name='purchasing__is_acti_e84ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'is_active'], name='purchasing__status_9b75e6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='purchasing__status_5ffbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['request_date'], name='purchasing__request_c4835c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['is_active'], name='purchasing__is_acti_7121fa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'is_active'], name='purchasing__status_d17ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['status'], name='purchasing__status_fc0e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['receiving_date'], name='purchasing__receivi_734730_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['is_active'], name='purchasing__is_acti_368176_idx'),
        ),
    ]
