# Generated by Django 5.2.4 on 2026-01-26 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número da Batelada"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPARATION", "Em Preparação"),
                            ("READY", "Pronta"),
                            ("IN_PRODUCTION", "Em Produção"),
                            ("COMPLETED", "Concluída"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PREPARATION",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "target_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade Alvo (kg)",
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="Quantidade Real (kg)",
                    ),
                ),
                (
                    "preparation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Preparação"
                    ),
                ),
                (
                    "production_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Início da Produção"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Material que compõe a batelada",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches_prepared",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Preparado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Batelada",
                "verbose_name_plural": "Bateladas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bin",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "code",
                    models.CharField(max_length=50, verbose_name="Código do Contentor"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Vazio"),
                            ("LOADED", "Carregado"),
                            ("IN_USE", "Em Uso"),
                            ("MAINTENANCE", "Em Manutenção"),
                        ],
                        default="EMPTY",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Capacidade máxima informativa",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Capacidade (kg)",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="Quantidade Atual (kg)",
                    ),
                ),
                (
                    "current_supplier_batch",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Lote do Fornecedor Atual",
                    ),
                ),
                (
                    "current_certificate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Certificado Atual"
                    ),
                ),
                (
                    "location_code",
                    models.CharField(
                        blank=True,
                        help_text="Estante, prateleira, posição",
                        max_length=50,
                        verbose_name="Código de Localização",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bins",
                        to="materials.material",
                        verbose_name="Material Atual",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bins",
                        to="inventory.warehouse",
                        verbose_name="Armazém",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contentor",
                "verbose_name_plural": "Contentores",
                "ordering": ["warehouse__code", "code"],
                "unique_together": {("warehouse", "code")},
            },
        ),
        migrations.CreateModel(
            name="BatchItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade (kg)",
                    ),
                ),
                (
                    "supplier_batch",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Lote do Fornecedor"
                    ),
                ),
                (
                    "certificate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Certificado"
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora da Coleta"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production.batch",
                        verbose_name="Batelada",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_items_collected",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coletado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_items",
                        to="production.bin",
                        verbose_name="Contentor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Batelada",
                "verbose_name_plural": "Itens da Batelada",
                "ordering": ["collected_at"],
            },
        ),
        migrations.CreateModel(
            name="BinHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Saída"),
                            ("EMPTY", "Esvaziamento"),
                            ("TRANSFER", "Transferência"),
                            ("ADJUSTMENT", "Ajuste"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimentação",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade (kg)",
                    ),
                ),
                (
                    "quantity_before",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=10,
                        verbose_name="Quantidade Antes (kg)",
                    ),
                ),
                (
                    "quantity_after",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=10,
                        verbose_name="Quantidade Depois (kg)",
                    ),
                ),
                (
                    "supplier_batch",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Lote do Fornecedor"
                    ),
                ),
                (
                    "certificate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número do Certificado"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Batelada para a qual o material foi usado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bin_history_entries",
                        to="production.batch",
                        verbose_name="Batelada",
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="production.bin",
                        verbose_name="Contentor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bin_movements_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico do Contentor",
                "verbose_name_plural": "Históricos dos Contentores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número da Ordem"
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Quantidade Planejada (kg)",
                    ),
                ),
                (
                    "produced_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="Quantidade Produzida (kg)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PLANNED", "Planejado"),
                            ("IN_PROGRESS", "Em Andamento"),
                            ("COMPLETED", "Concluído"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Início Planejada"
                    ),
                ),
                (
                    "planned_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim Planejada"
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora Início Real"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora Fim Real"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="materials.material",
                        verbose_name="Material a Produzir",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders_responsible",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Produção",
                "verbose_name_plural": "Ordens de Produção",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="production.productionorder",
                verbose_name="Ordem de Produção",
            ),
        ),
    ]
