# Generated by Django 6.0.1 on 2026-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bin",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Gerado automaticamente se não informado",
                max_length=50,
                verbose_name="Código do Contentor",
            ),
        ),
    ]
