# Generated by Django 5.2.4 on 2026-01-27 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_indexes'),
        ('materials', '0001_initial'),
        ('production', '0002_auto_generate_bin_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='production__status_9fdff2_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['is_active'], name='production__is_acti_dd52fc_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['status'], name='production__status_52b451_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['is_active'], name='production__is_acti_26346e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='production__status_b4dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['is_active'], name='production__is_acti_99ac46_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', 'is_active'], name='production__status_042847_idx'),
        ),
    ]
