#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 008

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task 008: Add Reports View to Production Module"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Running pre-flight checks..."

# Check Python
if ! command -v python &> /dev/null; then
    echo -e "${RED}Python not found. Please install Python 3.x${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python found: $(python --version)${NC}"

# Check if we're in the right directory
if [ ! -f "manage.py" ]; then
    echo -e "${RED}Error: manage.py not found. Are you in the project root?${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Project root directory confirmed${NC}"

# Check if database is accessible
if command -v psql &> /dev/null; then
    echo -e "${GREEN}✓ PostgreSQL client found${NC}"
else
    echo -e "${YELLOW}⚠ PostgreSQL client not found (optional)${NC}"
fi

# ============================================
# DATABASE MIGRATIONS
# ============================================

echo ""
echo "Checking database migrations..."
python manage.py migrate --check 2>/dev/null || {
    echo -e "${YELLOW}Migrations need to be applied${NC}"
    python manage.py migrate
}
echo -e "${GREEN}✓ Database migrations up to date${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Django development server..."
echo -e "${YELLOW}Note: This will run in the foreground. Press Ctrl+C to stop.${NC}"
echo ""

# Start Django development server
python manage.py runserver 0.0.0.0:8000 &
SERVER_PID=$!

# Wait for server to be ready
wait_for_service 8000 "Django Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django Backend: http://localhost:8000"
echo "  Production Reports: http://localhost:8000/production/reports/"
echo ""
echo "Admin URLs:"
echo "  Django Admin: http://localhost:8000/admin/"
echo ""
echo "Useful Commands:"
echo "  python manage.py check          - Run Django system checks"
echo "  python manage.py test           - Run test suite"
echo "  python manage.py shell          - Open Django shell"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

# Wait for server process
wait $SERVER_PID
