# Generated by Django 5.2.4 on 2025-07-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Foto do perfil do usuário",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
