# Generated by Django 5.2.4 on 2025-07-06 14:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Cor para identificação visual (hex)",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Material",
                "verbose_name_plural": "Categorias de Materiais",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Código interno (ex: AL7075, TI6AL4V)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("AL", "Alumínio"),
                            ("TI", "Titânio"),
                            ("SS", "Aço Inoxidável"),
                            ("IN", "Inconel"),
                            ("CO", "Cobalto-Cromo"),
                            ("CU", "Cobre"),
                            ("NI", "Níquel"),
                            ("OTHER", "Outros"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Material",
                    ),
                ),
                (
                    "composition",
                    models.JSONField(
                        default=dict,
                        help_text="Composição química em percentual {elemento: percentual}",
                        verbose_name="Composição Química",
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Densidade em g/cm³",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(25.0),
                        ],
                        verbose_name="Densidade (g/cm³)",
                    ),
                ),
                (
                    "melting_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Ponto de Fusão (°C)",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        default=dict,
                        help_text="Propriedades mecânicas, normas, etc.",
                        verbose_name="Especificações Técnicas",
                    ),
                ),
                (
                    "requires_certificate",
                    models.BooleanField(
                        default=True,
                        help_text="Material requer certificado de conformidade",
                        verbose_name="Requer Certificado",
                    ),
                ),
                (
                    "storage_requirements",
                    models.TextField(
                        blank=True, verbose_name="Requisitos de Armazenamento"
                    ),
                ),
                (
                    "safety_notes",
                    models.TextField(blank=True, verbose_name="Notas de Segurança"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="materials.materialcategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiais",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de Contato"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Telefone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Endereço")),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialSupplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "supplier_code",
                    models.CharField(
                        help_text="Código do material no catálogo do fornecedor",
                        max_length=100,
                        verbose_name="Código do Fornecedor",
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preço por Kg (R$)",
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Pedido Mínimo (Kg)",
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(verbose_name="Prazo de Entrega (dias)"),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True,
                        help_text="Material disponível para pedido",
                        verbose_name="Disponível",
                    ),
                ),
                (
                    "last_price_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização de Preço"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material-Fornecedor",
                "verbose_name_plural": "Materiais-Fornecedores",
                "ordering": ["material__code", "price_per_kg"],
                "unique_together": {("material", "supplier")},
            },
        ),
        migrations.AddField(
            model_name="material",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="materials",
                through="materials.MaterialSupplier",
                to="materials.supplier",
                verbose_name="Fornecedores",
            ),
        ),
    ]
