# Generated by Django 5.2.4 on 2025-08-01 14:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='composition',
        ),
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('symbol', models.CharField(help_text='Símbolo do elemento (ex: Al, Ti, V)', max_length=3, unique=True, verbose_name='Símbolo')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('atomic_number', models.IntegerField(unique=True, verbose_name='Número Atômico')),
                ('atomic_weight', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Peso Atômico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento Químico',
                'verbose_name_plural': 'Elementos Químicos',
                'ordering': ['atomic_number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialComposition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentual do elemento na composição (0.01-100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentual (%)')),
                ('is_max', models.BooleanField(default=False, help_text='Indica se este é um valor máximo permitido', verbose_name='Valor Máximo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.chemicalelement', verbose_name='Elemento Químico')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='materials.material', verbose_name='Material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Composição do Material',
                'verbose_name_plural': 'Composições dos Materiais',
                'ordering': ['-percentage'],
                'unique_together': {('material', 'element')},
            },
        ),
    ]
