# Generated by Django 5.2.4 on 2026-01-27 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active'], name='materials_m_is_acti_9d982b_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_type'], name='materials_m_materia_d75b87_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active', 'material_type'], name='materials_m_is_acti_67c250_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcategory',
            index=models.Index(fields=['is_active'], name='materials_m_is_acti_26cdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='materials_s_is_acti_7d2c29_idx'),
        ),
    ]
