#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Redis Caching Implementation

set -e

echo "========================================"
echo "Redis Caching Setup - Django LATECME"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if Redis is running
if ! nc -z localhost 6379 2>/dev/null; then
    echo -e "${YELLOW}Redis is not running. Starting Redis via docker-compose...${NC}"
    docker-compose up -d redis
    wait_for_service 6379 "Redis"
else
    echo -e "${GREEN}Redis is already running${NC}"
fi

# Check if PostgreSQL is running
if ! nc -z localhost 5432 2>/dev/null; then
    echo -e "${YELLOW}PostgreSQL is not running. Starting PostgreSQL via docker-compose...${NC}"
    docker-compose up -d postgres
    wait_for_service 5432 "PostgreSQL"
else
    echo -e "${GREEN}PostgreSQL is already running${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing Python dependencies..."

# Check if django-redis is installed
if ! python -c "import django_redis" 2>/dev/null; then
    echo -e "${YELLOW}Installing django-redis...${NC}"
    pip install django-redis
else
    echo -e "${GREEN}django-redis already installed${NC}"
fi

# ============================================
# RUN MIGRATIONS (if needed)
# ============================================

echo ""
echo "Applying database migrations..."
python manage.py migrate --no-input

# ============================================
# START DJANGO SERVER
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Redis:      localhost:6379"
echo "  PostgreSQL: localhost:5432"
echo "  Django:     http://localhost:8000"
echo ""
echo "Starting Django development server..."
echo ""

# Start Django server
python manage.py runserver 0.0.0.0:8000
