#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 007: Add Supplier Search API Endpoint

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo "Checking Python environment..."
if ! command -v python &> /dev/null; then
    echo -e "${RED}Python not found. Please install Python 3.11+${NC}"
    exit 1
fi

PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}Python ${PYTHON_VERSION} found${NC}"

# ============================================
# DATABASE (if using Docker)
# ============================================

if [ -f "docker-compose-dev.yml" ]; then
    echo ""
    echo "Starting PostgreSQL database..."
    docker-compose -f docker-compose-dev.yml up -d db
    wait_for_service 5432 "PostgreSQL"
fi

# ============================================
# DJANGO SETUP
# ============================================

echo ""
echo "Running Django migrations..."
python manage.py migrate --noinput

echo ""
echo "Collecting static files..."
python manage.py collectstatic --noinput --clear

# ============================================
# START DJANGO DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Django development server..."
python manage.py runserver 0.0.0.0:8000 &
SERVER_PID=$!

wait_for_service 8000 "Django"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django Backend:  http://localhost:8000"
echo "  Admin Panel:     http://localhost:8000/admin/"
echo "  API Endpoint:    http://localhost:8000/materials/api/suppliers/search/?q=test"
echo ""
echo "To stop the server, run: kill $SERVER_PID"
echo ""
echo -e "${YELLOW}Note: You need to be logged in to test the API endpoint${NC}"
echo ""
