#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 011

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check if Python is installed
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 not found. Please install Python 3.10+${NC}"
    exit 1
fi

# Check Python version
PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
echo -e "${GREEN}Python version: $PYTHON_VERSION${NC}"

# Check if virtual environment exists
if [ ! -d "venv" ] && [ ! -d ".venv" ]; then
    echo -e "${YELLOW}No virtual environment found. Creating one...${NC}"
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
else
    echo -e "${GREEN}Virtual environment found${NC}"
    if [ -d "venv" ]; then
        source venv/bin/activate
    else
        source .venv/bin/activate
    fi
fi

# ============================================
# START DATABASE (if using Docker)
# ============================================

if [ -f "docker-compose.yml" ]; then
    echo ""
    echo "Starting database services..."
    docker-compose up -d db
    sleep 5
fi

# ============================================
# DJANGO SETUP
# ============================================

echo ""
echo "Setting up Django..."

# Run migrations
echo "Running migrations..."
python manage.py migrate

# ============================================
# START DJANGO DEV SERVER
# ============================================

echo ""
echo "Starting Django development server..."
python manage.py runserver 0.0.0.0:8000 &
DJANGO_PID=$!

wait_for_service 8000 "Django"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django Backend:  http://localhost:8000"
echo "  Admin Panel:     http://localhost:8000/admin"
echo "  Materials API:   http://localhost:8000/materials/api/search/"
echo ""
echo "To stop services:"
echo "  kill $DJANGO_PID"
echo "  docker-compose down (if using Docker)"
echo ""
echo "To run tests:"
echo "  python manage.py test apps.materials"
echo ""
