#!/bin/bash

# Auto-Build Environment Setup
# Task: Enhance keyboard accessibility for modal dialogs
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START DJANGO DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Django development server..."
python manage.py runserver &

wait_for_service 8000 "Django"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django Server: http://localhost:8000"
echo ""
echo "Test URLs:"
echo "  Stock List (Movement Modal): http://localhost:8000/inventory/stock/"
echo "  Purchasing Orders: http://localhost:8000/purchasing/orders/"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for interrupt
wait
