# Generated by Django 4.2.27 on 2026-01-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("prefix", models.CharField(max_length=20)),
                ("current_value", models.PositiveIntegerField(default=0)),
                ("date_scope", models.DateField(blank=True, null=True)),
                ("padding", models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                "db_table": "core_sequence",
            },
        ),
    ]
