#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 014
# Add Database Indexes for Frequently Filtered Fields

set -e

echo "========================================"
echo "Database Index Migration Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if we're in the right directory
if [ ! -f "manage.py" ]; then
    echo -e "${RED}Error: manage.py not found. Please run this script from the project root.${NC}"
    exit 1
fi

# ============================================
# VERIFY PYTHON ENVIRONMENT
# ============================================

echo ""
echo "Checking Python environment..."

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: python3 not found${NC}"
    exit 1
fi

PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
echo -e "${GREEN}Python version: $PYTHON_VERSION${NC}"

# ============================================
# CHECK DATABASE CONNECTION
# ============================================

echo ""
echo "Verifying database connection..."

if python3 manage.py check --database default &> /dev/null; then
    echo -e "${GREEN}Database connection OK${NC}"
else
    echo -e "${RED}Error: Cannot connect to database${NC}"
    echo "Please ensure PostgreSQL is running and database credentials are correct in .env"
    exit 1
fi

# ============================================
# VERIFY CURRENT MIGRATION STATE
# ============================================

echo ""
echo "Checking current migration state..."

echo "Apps migration status:"
python3 manage.py showmigrations inventory purchasing production materials --plan

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Index Migration!"
echo "========================================"
echo ""
echo "This task will add database indexes to:"
echo "  - inventory app (StockMovement, InventoryCount, MaterialStock, Warehouse)"
echo "  - purchasing app (PurchaseRequest, PurchaseOrder, Receiving)"
echo "  - production app (ProductionOrder, Bin, Batch)"
echo "  - materials app (Material, Supplier, MaterialCategory)"
echo ""
echo "Target fields:"
echo "  - status (frequently filtered)"
echo "  - movement_type (frequently filtered)"
echo "  - is_active (frequently filtered)"
echo "  - date fields (frequently ordered by)"
echo ""
echo "Run the coder agent to implement the migrations."
echo ""
