# Generated by Django 5.2.4 on 2026-01-20 14:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_add_production_bin_batch_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('width_mm', models.DecimalField(decimal_places=2, help_text='Largura da etiqueta em milímetros', max_digits=6, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Largura (mm)')),
                ('height_mm', models.DecimalField(decimal_places=2, help_text='Altura da etiqueta em milímetros', max_digits=6, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Altura (mm)')),
                ('printer_dpi', models.IntegerField(choices=[(203, '203 DPI'), (300, '300 DPI')], default=203, verbose_name='Resolução da Impressora')),
                ('template_json', models.JSONField(default=dict, help_text='JSON com elementos do template', verbose_name='Configuração do Template')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template Padrão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Etiqueta',
                'verbose_name_plural': 'Templates de Etiquetas',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Impressora')),
                ('ip_address', models.GenericIPAddressField(help_text='IP da impressora na rede', verbose_name='Endereço IP')),
                ('port', models.IntegerField(default=9100, help_text='Porta TCP padrão: 9100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Porta TCP')),
                ('timeout_seconds', models.IntegerField(default=5, help_text='Timeout para conexão', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Timeout (segundos)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Impressora Padrão')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação')),
                ('last_test_success', models.BooleanField(blank=True, null=True, verbose_name='Última Verificação OK')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_printers', to='inventory.warehouse', verbose_name='Armazém Padrão')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Impressora',
                'verbose_name_plural': 'Configurações de Impressoras',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('epl_content', models.TextField(blank=True, help_text='Comandos EPL gerados', verbose_name='Comandos EPL')),
                ('bin_data_snapshot', models.JSONField(default=dict, help_text='Dados do bin no momento da impressão', verbose_name='Snapshot dos Dados')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Impresso em')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='inventory.bin', verbose_name='Contentor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='labels.printerconfiguration', verbose_name='Impressora')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='labels.labeltemplate', verbose_name='Template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabalho de Impressão',
                'verbose_name_plural': 'Trabalhos de Impressão',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='labels_prin_created_69e55e_idx'), models.Index(fields=['status'], name='labels_prin_status_4f6407_idx')],
            },
        ),
    ]
