#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 013

set -e

echo "========================================"
echo "Environment Setup - Remove Unused Plugins"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Verify we're in the correct directory
if [ ! -f "manage.py" ]; then
    echo -e "${RED}Error: Not in Django project root${NC}"
    echo "Expected to find manage.py"
    exit 1
fi

echo -e "${GREEN}✓ Django project root verified${NC}"

# Check Python version
PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
echo "Python version: $PYTHON_VERSION"

# Verify Django is installed
if ! python -c "import django" 2>/dev/null; then
    echo -e "${RED}Error: Django not installed${NC}"
    echo "Run: pip install -r requirements.txt"
    exit 1
fi

echo -e "${GREEN}✓ Django is installed${NC}"

# Verify target directory exists
if [ ! -d "staticfiles/plugins" ]; then
    echo -e "${YELLOW}Warning: staticfiles/plugins directory not found${NC}"
    echo "This may indicate it has already been removed or collectstatic hasn't been run yet."
else
    PLUGINS_SIZE=$(du -sh staticfiles/plugins | awk '{print $1}')
    PLUGINS_COUNT=$(ls -la staticfiles/plugins | wc -l)
    echo -e "${GREEN}✓ Target directory found${NC}"
    echo "  Size: $PLUGINS_SIZE"
    echo "  Items: $PLUGINS_COUNT"
fi

# Check staticfiles directory
if [ -d "staticfiles" ]; then
    TOTAL_SIZE=$(du -sh staticfiles | awk '{print $1}')
    echo -e "${GREEN}✓ staticfiles directory found${NC}"
    echo "  Total size: $TOTAL_SIZE"
else
    echo -e "${YELLOW}Note: staticfiles directory not found - collectstatic may not have been run${NC}"
fi

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Task: Remove unused staticfiles/plugins directory"
echo "Expected size reduction: ~23MB"
echo ""
echo "Next steps:"
echo "  1. Document current state (audit)"
echo "  2. Remove staticfiles/plugins/"
echo "  3. Verify application still works"
echo ""
