#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Add Python linting and code quality configuration

set -e

echo "========================================"
echo "Python Linting Configuration Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if in correct directory
if [ ! -f "manage.py" ]; then
    echo -e "${RED}Error: manage.py not found. Are you in the project root?${NC}"
    exit 1
fi

echo ""
echo "This script will set up the development environment for linting configuration."
echo ""
echo "Prerequisites:"
echo "  - Python >=3.10"
echo "  - pyproject.toml exists"
echo ""

# Check Python version
PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}✓${NC} Python version: $PYTHON_VERSION"

# Check if pyproject.toml exists
if [ -f "pyproject.toml" ]; then
    echo -e "${GREEN}✓${NC} pyproject.toml found"
else
    echo -e "${RED}✗${NC} pyproject.toml not found"
    exit 1
fi

# Optional: Create virtual environment if not exists
if [ ! -d ".venv" ]; then
    echo ""
    read -p "Create virtual environment (.venv)? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        python -m venv .venv
        echo -e "${GREEN}✓${NC} Virtual environment created"
        echo -e "${YELLOW}→${NC} Activate with: source .venv/bin/activate"
    fi
fi

echo ""
echo "========================================"
echo "Setup Notes"
echo "========================================"
echo ""
echo "This task will:"
echo "  1. Add ruff, mypy, bandit to pyproject.toml"
echo "  2. Configure each tool with Django-specific settings"
echo "  3. Add Makefile commands for easy execution"
echo "  4. Update documentation"
echo ""
echo "No services need to be running for this configuration task."
echo ""
echo "After dependencies are added, install with:"
echo "  pip install -e '.[dev]'  # If using pyproject.toml dev extras"
echo "  # or"
echo "  pip install ruff mypy bandit django-stubs"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
