# Generated by Django 5.2.4 on 2026-01-26 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Localização"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Armazém",
                "verbose_name_plural": "Armazéns",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Quantidade Reservada (kg)",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Reserva"
                    ),
                ),
                ("expiry_date", models.DateTimeField(verbose_name="Data de Expiração")),
                (
                    "purpose",
                    models.CharField(
                        help_text="Para que será usado o material",
                        max_length=200,
                        verbose_name="Finalidade",
                    ),
                ),
                (
                    "reference_document",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Documento de Referência",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reservado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouse",
                        verbose_name="Armazém",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de Estoque",
                "verbose_name_plural": "Reservas de Estoque",
                "ordering": ["-reservation_date"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Saída"),
                            ("TRANSFER", "Transferência"),
                            ("ADJUSTMENT", "Ajuste"),
                            ("RETURN", "Devolução"),
                            ("LOSS", "Perda"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimentação",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Compra"),
                            ("PRODUCTION", "Produção"),
                            ("SALE", "Venda"),
                            ("INTERNAL_USE", "Uso Interno"),
                            ("TRANSFER", "Transferência"),
                            ("INVENTORY_ADJUSTMENT", "Ajuste de Inventário"),
                            ("EXPIRED", "Vencido"),
                            ("DAMAGED", "Danificado"),
                            ("LOST", "Perdido"),
                            ("RETURN", "Devolução"),
                            ("OTHER", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Quantidade (kg)",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo Unitário (R$/kg)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Custo Total (R$)",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número do Lote"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número do Certificado"
                    ),
                ),
                (
                    "reference_document",
                    models.CharField(
                        blank=True,
                        help_text="Número da nota fiscal, pedido, etc.",
                        max_length=100,
                        verbose_name="Documento de Referência",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "destination_warehouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Para transferências",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_movements",
                        to="inventory.warehouse",
                        verbose_name="Armazém Destino",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouse",
                        verbose_name="Armazém",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reference_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Referência"
                    ),
                ),
                ("count_date", models.DateField(verbose_name="Data da Contagem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planejado"),
                            ("IN_PROGRESS", "Em Andamento"),
                            ("COMPLETED", "Concluído"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "counter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouse",
                        verbose_name="Armazém",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contagem de Inventário",
                "verbose_name_plural": "Contagens de Inventário",
                "ordering": ["-count_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCountItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "system_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Quantidade Sistema (kg)",
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Quantidade Contada (kg)",
                    ),
                ),
                (
                    "location_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Código de Localização"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventorycount",
                        verbose_name="Contagem",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Contagem",
                "verbose_name_plural": "Itens de Contagem",
                "ordering": ["material__code"],
                "unique_together": {("inventory_count", "material")},
            },
        ),
        migrations.CreateModel(
            name="MaterialStock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantidade Atual (kg)",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantidade Reservada (kg)",
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Estoque Mínimo (kg)",
                    ),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Estoque Máximo (kg)",
                    ),
                ),
                (
                    "location_code",
                    models.CharField(
                        blank=True,
                        help_text="Estante, prateleira, etc.",
                        max_length=50,
                        verbose_name="Código de Localização",
                    ),
                ),
                (
                    "last_movement_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data da Última Movimentação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouse",
                        verbose_name="Armazém",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque de Material",
                "verbose_name_plural": "Estoques de Materiais",
                "ordering": ["material__code", "warehouse__code"],
                "unique_together": {("material", "warehouse")},
            },
        ),
    ]
