# Generated by Django 5.2.4 on 2026-02-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_add_indexes"),
        ("inventory", "0002_alter_stockmovement_material_and_more"),
    ]

    operations = []
