#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 016

set -e

echo "========================================"
echo "Starting Django Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Python version
if ! command -v python &> /dev/null; then
    echo -e "${RED}Python is not installed${NC}"
    exit 1
fi

PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}Python $PYTHON_VERSION found${NC}"

# Check if database is accessible (optional - may not be needed for this refactor)
echo "Note: Database connection check skipped (not required for refactoring)"

# ============================================
# SETUP DJANGO
# ============================================

echo ""
echo "Setting up Django environment..."

# Check if manage.py exists
if [ ! -f "./manage.py" ]; then
    echo -e "${RED}manage.py not found - are you in the correct directory?${NC}"
    exit 1
fi

# Run migrations (ensure DB is up to date)
echo "Checking database migrations..."
python manage.py migrate --check || {
    echo -e "${YELLOW}Running migrations...${NC}"
    python manage.py migrate
}

# Collect static files
echo "Collecting static files..."
python manage.py collectstatic --noinput --clear 2>/dev/null || echo "Static files collection skipped"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Django development server..."

# Start Django dev server in background
python manage.py runserver 8000 &
DJANGO_PID=$!

# Wait for Django to be ready
wait_for_service 8000 "Django"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django:   http://localhost:8000"
echo "  Admin:    http://localhost:8000/admin/"
echo "  Inventory: http://localhost:8000/inventory/"
echo ""
echo "Django PID: $DJANGO_PID"
echo ""
echo "To stop services:"
echo "  kill $DJANGO_PID"
echo ""
echo "========================================"
