#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 020

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Split purchasing views.py"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if Python is available
if ! command -v python &> /dev/null; then
    echo -e "${RED}Python is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Python found${NC}"

# Check if manage.py exists
if [ ! -f "./manage.py" ]; then
    echo -e "${RED}manage.py not found - are you in the project root?${NC}"
    exit 1
fi
echo -e "${GREEN}Django project found${NC}"

# ============================================
# DATABASE CHECK
# ============================================

echo ""
echo "Checking database..."

# Try to run Django check to verify database connectivity
if python manage.py check --database default &> /dev/null; then
    echo -e "${GREEN}Database connection OK${NC}"
else
    echo -e "${YELLOW}Warning: Database connection issues detected${NC}"
    echo "You may need to start the database service"
fi

# ============================================
# START DJANGO DEV SERVER
# ============================================

echo ""
echo "Starting Django development server..."

# Start Django in background
python manage.py runserver 8000 &
DJANGO_PID=$!

# Wait for server to be ready
wait_for_service 8000 "Django"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django Dev Server: http://localhost:8000"
echo "  Admin Panel:       http://localhost:8000/admin/"
echo "  Purchasing App:    http://localhost:8000/purchasing/"
echo ""
echo "Process IDs:"
echo "  Django: $DJANGO_PID"
echo ""
echo "To stop services:"
echo "  kill $DJANGO_PID"
echo ""
echo "========================================"
