#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for task 010

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Add Bulk Status Change for Production Orders"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Django development server..."

# Start Django
python manage.py runserver &
wait_for_service 8000 "Django Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django:   http://localhost:8000"
echo "  Admin:    http://localhost:8000/admin"
echo "  Orders:   http://localhost:8000/production/orders/"
echo ""
echo "Development Tips:"
echo "  - View logs: tail -f /tmp/django.log"
echo "  - Stop server: pkill -f 'python manage.py runserver'"
echo "  - Database shell: python manage.py dbshell"
echo ""
