#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 015

set -e

echo "========================================"
echo "Starting Django Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if we're in the right directory
if [ ! -f "manage.py" ]; then
    echo -e "${RED}Error: manage.py not found. Are you in the project root?${NC}"
    exit 1
fi

# Check if virtual environment exists
if [ ! -d "venv" ] && [ ! -d ".venv" ]; then
    echo -e "${YELLOW}No virtual environment found. Creating one...${NC}"
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
else
    if [ -d "venv" ]; then
        source venv/bin/activate
    else
        source .venv/bin/activate
    fi
fi

echo -e "${GREEN}Virtual environment activated${NC}"

# Check if database is ready
echo "Checking database connection..."
python manage.py check --database default || {
    echo -e "${RED}Database connection failed${NC}"
    exit 1
}

echo -e "${GREEN}Database connection successful${NC}"

# Run migrations if needed
echo "Checking for pending migrations..."
python manage.py migrate --check || {
    echo -e "${YELLOW}Running migrations...${NC}"
    python manage.py migrate
}

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Django Development Server:"
echo "  Command: python manage.py runserver"
echo "  URL:     http://localhost:8000"
echo ""
echo "To start the server, run:"
echo "  python manage.py runserver"
echo ""
