#!/bin/bash

# Auto-Build Environment Setup for Task 018
# Extract Duplicated List View Pagination/Filtering into Reusable Utility
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Django Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if Python is installed
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 is not installed${NC}"
    exit 1
fi

# Check if PostgreSQL is running (for Docker setup)
if command -v docker-compose &> /dev/null; then
    echo "Docker Compose found - checking if database is running..."
    if docker-compose ps | grep -q postgres; then
        echo -e "${GREEN}PostgreSQL container is running${NC}"
    else
        echo -e "${YELLOW}Starting PostgreSQL via docker-compose...${NC}"
        docker-compose up -d postgres
        sleep 5
    fi
fi

# ============================================
# ACTIVATE VIRTUAL ENVIRONMENT
# ============================================

echo ""
echo "Activating virtual environment..."

if [ -d "venv" ]; then
    source venv/bin/activate
    echo -e "${GREEN}Virtual environment activated${NC}"
elif [ -d ".venv" ]; then
    source .venv/bin/activate
    echo -e "${GREEN}Virtual environment activated${NC}"
else
    echo -e "${YELLOW}No virtual environment found. Creating one...${NC}"
    python3 -m venv venv
    source venv/bin/activate
    echo -e "${GREEN}Virtual environment created and activated${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt
    echo -e "${GREEN}Dependencies installed${NC}"
fi

# ============================================
# RUN MIGRATIONS
# ============================================

echo ""
echo "Running database migrations..."

python manage.py migrate
echo -e "${GREEN}Migrations complete${NC}"

# ============================================
# START DJANGO DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Django development server..."

python manage.py runserver 0.0.0.0:8000 &
DJANGO_PID=$!

wait_for_service 8000 "Django"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Django:     http://localhost:8000"
echo "  Admin:      http://localhost:8000/admin/"
echo ""
echo "To stop the server, run: kill $DJANGO_PID"
echo ""
echo "To run tests:"
echo "  python manage.py test"
echo ""
echo "To access Django shell:"
echo "  python manage.py shell"
echo ""
